# Generated by Django 2.2.1 on 2019-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190519_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_picture',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/common/7/72/Default-welcomer.png', upload_to='images/'),
        ),
    ]
