# Generated by Django 2.2.1 on 2019-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190520_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
