# Generated by Django 2.2.1 on 2019-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190523_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
