# Generated by Django 2.2.1 on 2019-05-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=255)),
                ('answer', models.TextField(default='answer', max_length=1400)),
            ],
        ),
    ]
