# Generated by Django 2.2.1 on 2019-05-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190520_1638'),
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='departure_time',
            field=models.TimeField(default='7:00'),
        ),
        migrations.AddField(
            model_name='offer',
            name='destination',
            field=models.CharField(default='KBC', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='driver',
            field=models.CharField(default='full_name', max_length=70),
        ),
        migrations.AddField(
            model_name='offer',
            name='number_of_seats',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='passengers',
            field=models.CharField(default='full_name', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='regularity',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='__all__', max_length=15),
        ),
        migrations.AddField(
            model_name='offer',
            name='return_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='offer',
            name='route',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_location',
            field=models.CharField(default='choose start location', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='type_of_contact',
            field=models.CharField(choices=[('E', 'email'), ('PH', 'phone')], default='PH', max_length=2),
        ),
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(default='full_name', max_length=70)),
                ('ride_id', models.PositiveIntegerField()),
                ('drivers_name', models.CharField(default='full_name', max_length=70)),
                ('comments', models.TextField(blank=True, max_length=400)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileUser')),
            ],
        ),
        migrations.CreateModel(
            name='SeatApprovalRejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(default='full_name', max_length=70)),
                ('approve_reject', models.CharField(choices=[(1, 'Approve'), (0, 'Reject')], default=1, max_length=10)),
                ('comments', models.TextField(blank=True, max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.SeatRequest')),
            ],
        ),
    ]
