# Generated by Django 2.2.1 on 2019-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_auto_20190521_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='car_picture',
            field=models.ImageField(default='https://media-dmg.assets-cdk.com/websites/5.0-4142/websitesEar/websitesWebApp/css/common/images/en_US/noImage_large.png', upload_to='images/'),
        ),
    ]
