# Generated by Django 2.2.1 on 2019-05-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0008_auto_20190523_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='number_of_seats',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='regularity',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1),
        ),
    ]
