# Generated by Django 2.2.1 on 2019-05-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_auto_20190523_1351'),
        ('carpool', '0004_offer_car_picture'),
    ]

    operations = [
    ]
