# Generated by Django 2.2.1 on 2019-05-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_merge_20190523_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='driver',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7fb7d0280400> <django.db.models.query_utils.DeferredAttribute object at 0x7fb7d0280438>', max_length=70),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfileUser'),
        ),
        migrations.AlterField(
            model_name='seatapprovalrejection',
            name='approve_reject',
            field=models.CharField(choices=[('1', 'Approve'), ('0', 'Reject')], default=1, max_length=10),
        ),
    ]
