# Generated by Django 2.2.1 on 2019-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0012_auto_20190523_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='seatrequest',
            name='drivers_name',
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='driver',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=70),
        ),
    ]
