# Generated by Django 2.2.1 on 2019-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_auto_20190523_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='regularity',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], default='1', max_length=3),
        ),
    ]
