# Generated by Django 2.2.1 on 2019-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_auto_20190524_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_picture',
            field=models.ImageField(blank=True, default='https://media-dmg.assets-cdk.com/websites/5.0-4142/websitesEar/websitesWebApp/css/common/images/en_US/noImage_large.png', null=True, upload_to='images/'),
        ),
    ]
