# Generated by Django 2.2.1 on 2019-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0017_auto_20190524_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_picture',
            field=models.ImageField(blank=True, default='carpooling/static/media/images/default_car.png', null=True, upload_to='carpooling/static/media/images/'),
        ),
    ]
