# Generated by Django 2.2.1 on 2019-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0018_auto_20190524_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_picture',
            field=models.ImageField(blank=True, default='images/default_car.png', null=True, upload_to='images/'),
        ),
    ]
