# Generated by Django 2.2.1 on 2019-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0019_auto_20190524_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrequest',
            name='offer',
            field=models.ManyToManyField(to='carpool.Offer'),
        ),
    ]
