# Generated by Django 2.2.1 on 2019-05-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0020_seatrequest_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='ride_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk', to='carpool.Offer'),
        ),
    ]
