# Generated by Django 2.2.1 on 2019-05-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0022_remove_seatrequest_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='ride_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pk', to='carpool.Offer'),
        ),
    ]
