# Generated by Django 2.2.1 on 2019-05-25 12:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0024_auto_20190525_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='driver',
            field=multiselectfield.db.fields.MultiSelectField(default='<django.db.models.fields.related.ForeignKey>', max_length=200),
        ),
    ]
