# Generated by Django 2.2.1 on 2019-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0026_auto_20190526_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrequest',
            name='drivers_name',
            field=models.CharField(default='full_name', max_length=70),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='passenger',
            field=models.CharField(default='full_name', max_length=70),
        ),
        migrations.AlterField(
            model_name='seatrequest',
            name='ride_id',
            field=models.PositiveIntegerField(),
        ),
    ]
