# Generated by Django 2.2.1 on 2019-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0027_auto_20190526_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrequest',
            name='ride_id',
            field=models.CharField(default='null', max_length=700),
        ),
    ]
